### ISSUE TITLE
Consider renaning Global Context to Global State

### ISSUE THREAD

**Issue by shellforge** [warpforge/warpgrapher#57]
There are a lot of "contexts" throughout the code. Renaming this will a) more easily/intuitively communicate the function of this feature, b) help reduce the overloading of the term "context". 

Same with Request Context -> Request State.

**Comment by maldrake** [comment]
Right now, there are three, I believe.  There's the GraphQLContext trait provided by the Juniper crate that we implement in Warpgrapher. There's a GlobalContext we expose to the client of Warpgrapher, and a RequestContext that we expose to the client of Warpgrapher.

If I may propose an alternative solution.  It made sense to have both a GlobalContext and RequestContext when we were providing the server that accepted and responded to HTTP requests.  Now that we've split out the engine from the integration with any particular server, it could be entirely the client's responsibility to martial the context arguments to pass into the execute function, but mutably, so that extensions can modify data as needed.  Anything they pass to Warpgrapher will be passed for each invocation of execute.

Thus, I would propose we get rid of the GlobalContext entirely, keeping only a single Warpgrapher Context trait to be implemented by the client library.  Because we treat the GraphQLContext as entirely internal, for Warpgrapher's use, and expose only the Warpgrapher context to the client, this should mitigate the risk of any confusion.  The client library can source the data for their context anywhere they want, whether it's global across all requests or local to a single request.  They would then pass the context into the execute method, where it would be modified as needed by extension calls.

Not so sure about renaming to State, though... structures used for this purpose usually get called contexts.  I'm convinceable, though.

**Comment by shellforge** [comment]
Interesting idea - I'll give this some thought.
