### ISSUE TITLE
Relationship delete operation appears broken

### ISSUE THREAD

**Issue by drkatie** [warpforge/warpgrapher#65]
Given the following state:
```
{
  "data": {
    "User": [
      {
        "id": "2943efbf-fe4f-490a-8acf-c5d93c95a498",
        "name": "katie",
        "owns": [
          {
            "dst": {
              "__typename": "World",
              "id": "5e8b4e74-5796-4f84-ac07-26430e9593ca",
              "name": "katiesworld"
            }
          }
        ]
      },
      {
        "id": "6a39e3b2-79fc-4630-81ea-5e5a38f40de4",
        "name": "javi",
        "owns": [
          {
            "dst": {
              "__typename": "World",
              "id": "f1ef7315-ab29-4762-97f2-31cfb16bd30c",
              "name": "javisworld"
            }
          }
        ]
      }
    ]
  }
}
```
Attempted the following query (which had no effect):
```
mutation {
  UserOwnsDelete (input: {
    match: {
      src: {
        User: {
          name: "javi"
        }
      }
      dst: {
        World: {
          name: "javisworld"
        }
      }
    }
  }
  )
}
```

When the `src` block is omitted, the operation succeeds.

**Comment by maldrake** [comment]
The changes that added Neptune support made some significant changes -- dare I say improvements? -- to the way queries are constructed. Those changes were merged after this bug was filed. It's possible they fixed this bug as well, but I'd want to test to be sure. @drkatie, I don't suppose you still have the configuration files and whatever else you used to uncover this problem, and could give it another try or send them to me?

If not, it's no problem for me to create a test case. I just thought I'd go the lazy route if you happened to still have something conveniently at hand.
